version: "3"

services:
  db:
    image: mysql/mysql-server:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - rummy_game_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: localhostroot
      MYSQL_DATABASE: rummy_game
    ports:
      - 3333:3306

  rummygame:
    build: ./rummygame
    volumes:
      - ./rummygame:/var/www/html/rummygame
    depends_on:
      - db
    restart: always
    links:
      - db:mysql
    ports:
      - "5000:80"

volumes:
  rummy_game_data:
